// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKB7wsjX7h36SeXBccMEQCZY6O1Rye8Yc',
    appId: '1:654194180458:web:4d5adb23151dc19ef8a513',
    messagingSenderId: '654194180458',
    projectId: 'lift-access-control',
    authDomain: 'lift-access-control.firebaseapp.com',
    storageBucket: 'lift-access-control.appspot.com',
    measurementId: 'G-0HW3DZ3YM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9QSTkTQNcMGfni3NpnidQNYBEVaiZjxs',
    appId: '1:654194180458:android:d68e8cdffc28dc31f8a513',
    messagingSenderId: '654194180458',
    projectId: 'lift-access-control',
    storageBucket: 'lift-access-control.appspot.com',
  );

}
