name: Elivatme
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  fluttertoast: 8.2.4
  provider: ^6.0.5
  cloud_firestore: 4.15.9
  firebase_storage: 11.6.11

  shared_preferences: ^2.0.8


  syncfusion_flutter_charts: 21.2.4
  intl: 0.17.0
  mrx_charts: ^0.1.3
  fl_chart: ^0.67.0
  spline_chart: ^0.0.2


  pdf: ^3.6.1 # Add the dependency for generating PDF documents
  path_provider: ^2.0.2 # Add the dependency for accessing the device's file system
  open_file: ^3.0.3 # Add the dependency for opening files using platform-specific apps
  line_awesome_flutter: ^1.0.1

  rename_app: ^1.3.2

  page_view_dot_indicator: ^2.3.0

    # switch animation between light and dark theme
  animated_theme_switcher: ^2.0.10


  # pick image
  image_picker: ^0.8.4+4 # Add this line if it's missing

  path: any
  charts_flutter: ^0.12.0
  flutter_chart: ^0.1.6
  url_launcher: ^6.2.6
  random_string: ^2.3.1
dependency_overrides:
  intl: 0.17.0 # Specify the version of intl here



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  image_path: "assets/images/logo_light.png" 
  

  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true
    
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  pedantic: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_light.png
    - assets/default_profile.jpg
    - assets/images/
    - assets/icons/

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
