// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMZ-vDKN14ae88lC95e-CYoFyPe2AtLA',
    appId: '1:999095028568:web:51bdcc329eddb9b5edb32d',
    messagingSenderId: '999095028568',
    projectId: 'liftguard-pro',
    authDomain: 'liftguard-pro.firebaseapp.com',
    databaseURL: 'https://liftguard-pro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftguard-pro.appspot.com',
    measurementId: 'G-16N7D9P53T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wIINECX18wN_rqS4eTyif1OsvSNtwhc',
    appId: '1:999095028568:android:abbdbdb62494cc11edb32d',
    messagingSenderId: '999095028568',
    projectId: 'liftguard-pro',
    databaseURL: 'https://liftguard-pro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftguard-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFce9r3AtrasiMfqBVObfC6csTj3QMBPA',
    appId: '1:999095028568:ios:f87415a890a900aeedb32d',
    messagingSenderId: '999095028568',
    projectId: 'liftguard-pro',
    databaseURL: 'https://liftguard-pro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftguard-pro.appspot.com',
    iosClientId: '999095028568-saco2j0gbk90h97mf29ba7o6545uh3ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFce9r3AtrasiMfqBVObfC6csTj3QMBPA',
    appId: '1:999095028568:ios:f87415a890a900aeedb32d',
    messagingSenderId: '999095028568',
    projectId: 'liftguard-pro',
    databaseURL: 'https://liftguard-pro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftguard-pro.appspot.com',
    iosClientId: '999095028568-saco2j0gbk90h97mf29ba7o6545uh3ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
